# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: todo-app-dev
    ports:
      - "4200:4200"
    volumes:
      - ./:/app
      - /app/node_modules
